export default ({
    userNotFound: (message) => ({ status: 'USER_NOT_FOUND', message: message ?? 'El usuario no existe' }),
    accountDeactivated: (message) => ({ status: 'ACCOUNT_DEACTIVATED', message: message ?? 'Tu cuenta se encuentra desactivada' }),
    incorrectCodeVerified: (message) => ({ status: 'CODE_INCORRECT', message: message ?? 'Código de verificación incorrecto. Por favor verifique su correo e intentelo de nuevo.' }),
    expireCode: (message) => ({ status: 'EXPIRED_CODE', message: message ?? 'El codigo de verificacion ha caducado, intenta enviando de nuevo el correo' }),
    dataAlreadyExist: (message) => ({ status: 'USER_ALREADY_EXIST', message: message ?? 'El correo o el username ya esta en uso' }),
    passwordIncorrect: (message) => ({ status: 'PASSWORD_INCORRECT', message: message ?? 'Tu contraseña no es correcta' }),
    internalError: (message) => ({ status: 'INTERNAL_SERVER_ERROR', message: message ?? 'Ups! Estamos experimentando problemas técnicos en este momento.' }),
    invalidBodyKeys: (message) => ({ status: 'INVALID_BODY_KEYS', message: message ?? 'La estructura del body es incorrecta, faltan keys o son incorrectas' }),
    invalidDateFormat: (message) => ({ status: 'INVALID_DATE_FORMAT', message: message ?? 'El formato de fecha es incorrecto' }),
    invalidFormatPassword: (message) => ({ status: 'INVALID_PASSWORD_FORMAT', message: message ?? 'El formato de la contraseña es incorrecto' }),
    invalidEmailFormat: (message) => ({ status: 'INVALID_EMAIL_FORMAT', message: message ?? 'El correo electronico no es valido' }),
    insufficientPermits: (message) => ({ status: 'INSUFFICIENT_PERMITS', message: message ?? 'No tiene el permiso para realizar esta accion' }),
    accountBanned: (message) => ({ status: 'ACCOUNT_BANNED', message: message ?? 'Su cuenta se encuentra banneada en estos momentos' }),
}) 